services:
  - type: web
    name: liam-ig-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: APP_SECRET
        sync: false
      - key: IG_TOKEN
        sync: false
      - key: GEMINI_KEY
        sync: false
